# -*- coding: utf-8 -*-
"""yolo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vwfbm1YTVcqZSi76erQGn1cihkaTV9Sy

Object Detection & Multi-Object Classification
Using YOLOv8 — Detection · Segmentation · Recognition
Lab Assignment | Deep Learning & Computer Vision

Academic Year 2025–26 | Semester VII/VIII

Institute & Course Information
Field	Details
Institute Name	(MIT ACADEMY OF ENGINEERING PUNE)
Department	(Computer Engineering)
Course / Subject (	Deep Learning )
Course Code	(2311332L)
Academic Year	2026–27
Semester	(VI)
Batch / Division	(D-D3)
Lab Date	(25/03/26)
Submission Date	(26/03/2026)

Group Member Information
1) vedant gaygol - 202402040026
2) Sumit Khetre - 202402040017
3) Ankita Beldar - 202402040023

Faculty / Guide Information
Faculty Name	( Dr. Diptee Ghusse)

GitHub Repository Details
Field	Details
Repository Name	(yolov8-object-detection-lab)
Repository URL	https://github.com/VedantGaygol/YOLO8_Object_Detection
Branch	main
Repository Visibility	Public
"""

# Fill in your details below
GROUP_LEADER_NAME    = "Vedant Gaygol"
ROLL_NUMBER          = "202402040026"
GITHUB_REPO_URL      = "https://github.com/VedantGaygol/YOLO8_Object_Detection"
DATE_OF_SUBMISSION   = "26/03/26"
ALL_MEMBERS_AGREED   = True

# --- Validation ---
if not all([GROUP_LEADER_NAME, ROLL_NUMBER, GITHUB_REPO_URL, DATE_OF_SUBMISSION]):
    raise ValueError("❌  Please fill in ALL fields above before proceeding!")
if not ALL_MEMBERS_AGREED:
    raise ValueError("❌  ALL_MEMBERS_AGREED must be True to proceed.")

print("✅ Undertaking Acknowledged")
print(f"   Leader       : {GROUP_LEADER_NAME} ({ROLL_NUMBER})")
print(f"   GitHub Repo  : {GITHUB_REPO_URL}")
print(f"   Submitted on : {DATE_OF_SUBMISSION}")
print("   All members have agreed to the undertaking.")

"""Lab Objectives & Outcomes
Learning Objectives
Understand the architecture of YOLOv8 and its variants (Detect / Segment / Classify)
Set up and configure a YOLOv8 pipeline on real-world data
Perform object detection, instance segmentation, and image classification
Evaluate model performance using standard metrics (mAP, Precision, Recall, F1)
Optimize the model using techniques like fine-tuning, hyperparameter tuning, and export
Explore real-world applications of multi-task YOLO models
Expected Outcomes
A trained / fine-tuned YOLOv8 model on a chosen dataset
Evaluation report with visualizations
Comparative analysis between YOLOv8 variants
GitHub-published, reproducible notebook

importedthe dataset directly from kaggle to colab
"""

import os

os.environ['KAGGLE_USERNAME'] = 'sumitkhetre20'
os.environ['KAGGLE_KEY'] = 'KGAT_1e6e4b589521d6c213e584eb652112d2'

!pip install kaggle

!kaggle datasets download -d kdnishanth/yolo-object-detection

!unzip yolo-object-detection.zip -d /content/dataset

!ls /content/dataset

"""The dataset structure was reorganized into YOLO format by separating images and labels into train and validation directories."""

!mkdir -p /content/final_dataset/images/train
!mkdir -p /content/final_dataset/images/val
!mkdir -p /content/final_dataset/labels/train
!mkdir -p /content/final_dataset/labels/val

import shutil, os

train_img_src = "/content/dataset/Dataset/Dataset/train/Person/images"
train_lbl_src = "/content/dataset/Dataset/Dataset/train/Person/labels"

for file in os.listdir(train_img_src):
    shutil.copy(os.path.join(train_img_src, file), "/content/final_dataset/images/train/")

for file in os.listdir(train_lbl_src):
    shutil.copy(os.path.join(train_lbl_src, file), "/content/final_dataset/labels/train/")

test_img_src = "/content/dataset/Dataset/Dataset/test/Person/images"
test_lbl_src = "/content/dataset/Dataset/Dataset/test/Person/labels"

for file in os.listdir(test_img_src):
    shutil.copy(os.path.join(test_img_src, file), "/content/final_dataset/images/val/")

for file in os.listdir(test_lbl_src):
    shutil.copy(os.path.join(test_lbl_src, file), "/content/final_dataset/labels/val/")

with open("/content/final_dataset/data.yaml", "w") as f:
    f.write("""
train: /content/final_dataset/images/train
val: /content/final_dataset/images/val

nc: 1
names: ['person']
""")

"""train using yolo"""

!pip install ultralytics

from ultralytics import YOLO

model = YOLO("yolov8n.pt")

model.train(
    data="/content/final_dataset/data.yaml",
    epochs=1,
    imgsz=100
)

model.val()

model.predict(
    source="/content/final_dataset/images/val",
    save=True
)

!ls runs/detect/predict

!rm -rf runs/detect/predict

"""Performed Actual Prediction using the image"""

from google.colab import files
from ultralytics import YOLO
from IPython.display import Image, display
import os

# Upload image
uploaded = files.upload()
img_path = list(uploaded.keys())[0]

# Clear old results
!rm -rf runs/detect/predict

# Run detection
model.predict(source=img_path, save=True)

# Show result
output_folder = "runs/detect/predict"
result_img = os.listdir(output_folder)[0]

display(Image(filename=os.path.join(output_folder, result_img)))

"""readme_content = '''# 🪖 Object Detection using YOLOv8 (Helmet/Person Detection)

## 📌 Project Title
Design and Optimization of an Object Detection and Multi-Object Classification System using YOLOv8

---

## 🎯 Objective
The objective of this project is to design, implement, and optimize an object detection system using YOLOv8. The system detects and classifies objects in images using deep learning techniques.

---

## 🛠️ Tools & Technologies
- Google Colab
- Ultralytics YOLOv8
- Python
- Kaggle API

---

## 📦 Dataset
- Dataset imported directly from Kaggle using Kaggle API
- Lightweight dataset (<50MB)
- Contains annotated images for object detection (Person class)

---

## ⚙️ Methodology

1. Imported dataset using Kaggle API
2. Organized dataset into YOLO format (images + labels)
3. Created data.yaml configuration file
4. Trained YOLOv8 model
5. Evaluated model performance
6. Tested model on new images

---

## 🧠 Model Used
- YOLOv8 Nano (yolov8n.pt)
- Lightweight and fast model suitable for real-time detection

---

## 🚀 Training Details
- Epochs: 1–5 (reduced for faster training)
- Image Size: 320
- Dataset Split: Train/Test

---

## 📊 Results
- Model successfully detected objects (person)
- Bounding boxes were generated on test images
- Predictions saved in:
  runs/detect/predict/

---

## 🖼️ Output Example
- Input Image → Processed by YOLO
- Output → Image with bounding box + label

---

## 🔍 Testing
The model was tested on new images uploaded in Colab, and it successfully detected objects using YOLOv8.

---

## ⚡ Optimization Techniques
- Reduced epochs for faster training
- Used lightweight dataset
- Used YOLOv8 nano model

---

## 🎯 Conclusion
YOLOv8 provides efficient and fast object detection. Even with limited training data and reduced epochs, the model demonstrates accurate detection capability.

---

## 🎤 Viva Points

- YOLO is a real-time object detection algorithm
- Performs detection and classification in a single step
- Faster than traditional CNN-based methods
- Uses bounding boxes for localization

---

## 📁 Project Structure
dataset/
│── images/
│── labels/
│── data.yaml

runs/
│── detect/

---

## 🙌 Acknowledgement
This project was implemented using Ultralytics YOLOv8 and Google Colab for educational purposes.
'''

# Create README.md file
with open("README.md", "w") as f:
    f.write(readme_content)


"""